# Site settings
title: Jen's Profile
email: mcphail.jen@gmail.com
description: Jen's resume & portfolio
baseurl: "/patchwork-gh-pages-24"
url: "http://jenmcphail.github.io"
twitter_username: jenmcphail
github_username:  jenmcphail
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index